### ISSUE TITLE
Access to repo settings

### ISSUE THREAD

**Issue by cogdog** [cc-archive/opened16#1]
requesting to manage settings here

**Comment by mattl** [comment]
The only thing you can't do is add more people, it seems... what else needs to change?

**Comment by cogdog** [comment]
Make gh-pages default branch, ok to delete master, just a little histed web site. Thx

**Comment by mattl** [comment]
Cool. I'll give this to @robmyers who is working on the CC Cert stuff.

**Comment by rheaplex** [comment]
gh-pages made default branch, master deleted (can be undeleted if needed).
